"""initial_domain_schema

Revision ID: ce21a1451fc6
Revises:
Create Date: 2026-07-31 21:25:21.473765
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ce21a1451fc6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("ADMIN", "EVALUATOR", name="user_role"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_table(
        "audio_batches",
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("total_files", sa.Integer(), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "VALIDATED",
                "QUEUED",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="batch_status",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audio_batches_status"), "audio_batches", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_audio_batches_uploaded_by"),
        "audio_batches",
        ["uploaded_by"],
        unique=False,
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=128), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_resource_id"), "audit_logs", ["resource_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_resource_type"),
        "audit_logs",
        ["resource_type"],
        unique=False,
    )
    op.create_table(
        "audio_assets",
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("channels", sa.Integer(), nullable=True),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column(
            "processing_status",
            sa.Enum(
                "UPLOADED",
                "VALIDATED",
                "PROCESSING",
                "PROCESSED",
                "FAILED",
                name="audio_status",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["batch_id"], ["audio_batches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key", name="uq_audio_assets_storage_key"),
    )
    op.create_index(
        op.f("ix_audio_assets_batch_id"), "audio_assets", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_audio_assets_processing_status"),
        "audio_assets",
        ["processing_status"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "QUEUED",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="job_status",
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100", name="ck_jobs_progress_range"
        ),
        sa.CheckConstraint("retry_count >= 0", name="ck_jobs_retry_count_nonnegative"),
        sa.ForeignKeyConstraint(["batch_id"], ["audio_batches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", name="uq_jobs_batch_id"),
    )
    op.create_index(op.f("ix_jobs_batch_id"), "jobs", ["batch_id"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "predictions",
        sa.Column("audio_asset_id", sa.UUID(), nullable=False),
        sa.Column(
            "emotional_tone",
            sa.Enum(
                "NEUTRAL",
                "SATISFIED",
                "FRUSTRATED",
                "UPSET",
                "DISTRESSED",
                name="emotion_tone",
            ),
            nullable=False,
        ),
        sa.Column(
            "emotional_intensity",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="emotion_intensity"),
            nullable=False,
        ),
        sa.Column("background_noise_present", sa.Boolean(), nullable=False),
        sa.Column("background_noise_type", sa.String(length=128), nullable=False),
        sa.Column(
            "background_noise_severity",
            sa.Enum("NONE", "LOW", "MEDIUM", "HIGH", name="noise_severity"),
            nullable=False,
        ),
        sa.Column(
            "audio_quality",
            sa.Enum(
                "CLEAR", "SLIGHTLY_IMPAIRED", "SEVERELY_IMPAIRED", name="audio_quality"
            ),
            nullable=False,
        ),
        sa.Column("speaker_overlap", sa.Boolean(), nullable=False),
        sa.Column("long_silence", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_persisted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name="ck_predictions_confidence_range",
        ),
        sa.ForeignKeyConstraint(
            ["audio_asset_id"], ["audio_assets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("audio_asset_id", name="uq_predictions_audio_asset_id"),
    )
    op.create_index(
        op.f("ix_predictions_audio_asset_id"),
        "predictions",
        ["audio_asset_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_predictions_audio_asset_id"), table_name="predictions")
    op.drop_table("predictions")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_batch_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_audio_assets_processing_status"), table_name="audio_assets")
    op.drop_index(op.f("ix_audio_assets_batch_id"), table_name="audio_assets")
    op.drop_table("audio_assets")
    op.drop_index(op.f("ix_audit_logs_resource_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_audio_batches_uploaded_by"), table_name="audio_batches")
    op.drop_index(op.f("ix_audio_batches_status"), table_name="audio_batches")
    op.drop_table("audio_batches")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
